parameters:

  type: terraform
  
  kapitan:
    vars:
      target: ${name}

    compile:

      - output_path: terraform
        output_type: json
        input_paths:
          - templates/terraform/main.jsonnet
        input_type: jsonnet

      - output_path: pillar
        input_paths:
          - templates/pillar
        input_type: jinja2