services:
  consul:
    command: agent -dev -client 0.0.0.0 -config-file /etc/consul/config.json
    depends_on:
      - fluentd
    environment:
      VIRTUAL_HOST: consul.local
      VIRTUAL_PORT: 8500
    image: consul
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.consul
    volumes:
      - ./config/consul:/etc/consul/config.json
  elasticsearch:
    container_name: elasticsearch
    environment:
      VIRTUAL_HOST: elastic.local
      VIRTUAL_PORT: 9200
    healthcheck:
      interval: 30s
      retries: 5
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo
        0; else echo 1; fi
      timeout: 10s
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
  fluentd:
    depends_on:
      - elasticsearch
    image: 1a70a1114901
    links:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./config/fluent:/fluentd/etc/fluent.conf
  gitlab:
    depends_on:
      - redis
      - timescale
      - fluentd
    environment:
      - VIRTUAL_HOST=gitlab.local
      - VIRTUAL_PORT=80
      - DB_ADAPTER=postgresql
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_USER=salt
      - DB_PASS=salt
      - DB_NAME=gitlabhq_production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITLAB_ROOT_PASSWORD=password
      - GITLAB_ROOT_EMAIL=root@localhost
    image: sameersbn/gitlab:11.4.0
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.gitlab
    restart: always
  grafana:
    depends_on:
      - fluentd
    environment:
      VIRTUAL_HOST: grafana.local
      VIRTUAL_PORT: 3000
    image: grafana/grafana
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.grafana
  kibana:
    depends_on:
      - fluentd
      - elasticsearch
    environment:
      - VIRTUAL_HOST=kibana.local
      - VIRTUAL_PORT=5601
    image: kibana:6.4.1
    links:
      - elasticsearch
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.kibana
    ports:
      - 5601:5601
  minion:
    command: salt-minion
    depends_on:
      - fluentd
    image: 79afac088483
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.minion
    volumes:
      - ./salt/:/srv/salt/
      - ./pillar/:/srv/pillar/
      - ./pki/minion:/etc/salt/pki/
  nginx-proxy:
    depends_on:
      - fluentd
    image: jwilder/nginx-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    command:
      - --loglevel warning
    depends_on:
      - fluentd
    image: sameersbn/redis:4.0.9-1
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.redis
  salt:
    command: salt-master
    depends_on:
      - fluentd
    image: 79afac088483
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.salt
    ports:
      - 4505
      - 4506
      - 8000
    volumes:
      - ./config/salt-config:/etc/salt/master
      - ./salt/:/srv/salt/
      - ./pillar/:/srv/pillar/
      - ./pki/:/etc/salt/pki/
  timescale:
    depends_on:
      - fluentd
    environment:
      - DB_USER=salt
      - PROVISION=true
      - DB_PASS=salt
      - DB_NAME=salt,gitlabhq_production
      - DB_EXTENSION=pg_trgm,zombodb
    image: a9d84fee837b
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.timescale
    volumes:
      - ./database:/data
  vault:
    depends_on:
      - fluentd
      - consul
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VIRTUAL_HOST: vault.local
      VIRTUAL_PORT: 8200
    image: vault
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: motherbase.vault
    ports:
      - 8200:8200
    volumes:
      - ./vault:/config
version: '3'
