driver:
  name: docker
  use_sudo: false
  privileged: true
  require_chef: true
  forward:
    - 80:80
    - 443:443
  provision_command:
    - DEBIAN_FRONTEND=noninteractive apt-get update -y
    - mkdir -p /run/sshd

transport:
  name: sftp

provisioner:
  name: salt_solo
  salt_install: bootstrap
  is_file_root: true
  require_chef: true
  salt_copy_filter:
    - .git
    - .gitignore
    - .gemfile
  state_top:
    base:
      "*":
        - init-sys
  pillars:
    top.sls:
      base:
        "*":
          - init-sys
  pillars_from_files:
    init-sys.sls: pillar.init-sys.example

platforms:
  - name: ubuntu
    driver_config:
      run_command: /bin/systemd

verifier:
  name: inspec

suites:
  - name: default

